spring:
  application:
    name: aim

  datasource:
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
jwt:
  secret:
    key: ${JWT_SECRET}
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG

